FROM eclipse-temurin:17-ubi9-minimal

ENV SBT_VERSION=1.9.6

# setup the repo for sbt
RUN rm -f /etc/yum.repos.d/bintray-rpm.repo \
 && curl -L https://www.scala-sbt.org/sbt-rpm.repo > sbt-rpm.repo \
 && mv sbt-rpm.repo /etc/yum.repos.d/

# install some packages and sbt
RUN INSTALL_PKGS="nano curl net-tools sbt-$SBT_VERSION" \
 && microdnf install -y $INSTALL_PKGS \
 && rpm -V $INSTALL_PKGS \
 && microdnf clean all -y

# building, testing, packaging
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN sbt -v +deploy/stage

ENTRYPOINT ["kafkakewl-deploy/target/universal/stage/bin/kafkakewl-deploy"]
