FROM eclipse-temurin:21-jdk-ubi9-minimal

# install some packages
RUN INSTALL_PKGS="findutils net-tools" \
 && microdnf install -y $INSTALL_PKGS \
 && rpm -V $INSTALL_PKGS \
 && microdnf clean all -y

# building, testing, packaging
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN ./gradlew build

ENTRYPOINT ["java", "-jar", "kafkakewl-deploy/build/libs/kafkakewl-deploy-all.jar"]
