/* do not remove or change this comment as this indicates the top of the file for the spotless licenseHeaderFile
 *
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    val ktor_version: String by settings
    val plugin_serialization_version: String by settings
    val spotless_version: String by settings
    plugins {
        id("io.ktor.plugin") version ktor_version
        id("org.jetbrains.kotlin.plugin.serialization") version plugin_serialization_version
        id("com.diffplug.spotless") version spotless_version
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "kafkakewl-vnext-kotlin"
include("kafkakewl-common", "kafkakewl-deploy", "kafkakewl-domain", "kafkakewl-metrics", "kafkakewl-utils")
