name: Build, test and package
on:
  pull_request:
jobs:
  build-test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Build, test and package
        run: sbt -v +deploy/stage +metrics/stage
