name: Build and publish the docker image
on:
  push:
    tags:
      - v*
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Sets the image name
        run: |
          echo "IMAGE=ghcr.io/marshallwace/kafkakewl-deploy" >> $GITHUB_ENV
      - name: Extract the tag version
        if: "startsWith(github.ref, 'refs/tags/v')"
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mwam-ci
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push tag
        uses: docker/build-push-action@v5
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          context: .
          file: ./Dockerfile-kafkakewl-deploy
          platforms: linux/amd64
          tags: ${{ env.IMAGE }}:${{ env.VERSION }}
          push: true
          cache-to: type=local,dest=/tmp/.buildx-cache
